### ISSUE TITLE
训练时，gpu占用并不满，但是增加batch_size会提示显存溢出，请问这是什么问题？

### ISSUE THREAD

**Issue by sangwz** [bubbliiiing/yolov4-tf2#12]
![image](https://user-images.githubusercontent.com/58506571/101428273-582b0480-393b-11eb-993f-e36963477fc9.png)
![image](https://user-images.githubusercontent.com/58506571/101428361-83adef00-393b-11eb-90a4-9b034c2285e7.png)
是我gpu型号的问题吗？

**Comment by bubbliiiing** [comment]
你这看起来都没用GPU，环境对吗

**Comment by sangwz** [comment]
环境和你的有点差别，不过应该没问题。我改用你的torch版本了

**Comment by bubbliiiing** [comment]
NP
