### ISSUE TITLE
Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled

### ISSUE THREAD

**Issue by sangwz** [bubbliiiing/yolov4-tf2#13]
运行完一个epoch之后，会有标题的提示，训练仍然继续。
[tensorflow](https://github.com/tensorflow/tensorflow/issues/35100)，采用该回答的方法也没能去除。
请问这个错误对训练结果有影响吗？该如何解决。

**Comment by bubbliiiing** [comment]
我没见过这个错误…不知道会不会有影响，你版本一样吗

**Comment by sangwz** [comment]
tf2.1，回头再试试你的版本吧。
