### ISSUE TITLE
predict.py 运行出现错误

### ISSUE THREAD

**Issue by 348872575** [bubbliiiing/yolov4-tf2#4]
我的环境：
window10+pycharm
conda 下的tensorflow-gpu2.2包含的库如下：
 Name                 Version                   Build  Channel
absl-py                   0.9.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2020.6.24                     0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20                py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.1.243             h74a9793_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudnn                     7.6.5                cuda10.1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                   py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
freetype                  2.10.2               hd328e21_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gast                      0.3.3                    pypi_0    pypi
google-auth               1.18.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.30.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf5                      1.8.20               hac2f561_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
icc_rt                    2019.0.0             h0cc432a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
icu                       58.2                 ha925a31_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
idna                      2.10                     pypi_0    pypi
importlib-metadata        1.7.0                    pypi_0    pypi
intel-openmp              2020.1                      216    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
joblib                    0.16.0                   pypi_0    pypi
jpeg                      9b                   hb83a4c4_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.2.0            py37h74a9793_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libopencv                 3.4.2                h20b85fd_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libpng                    1.6.37               h2a8f88b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtiff                   4.1.0                h56a325e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lz4-c                     1.9.2                h62dcd97_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
markdown                  3.2.2                    pypi_0    pypi
matplotlib                3.2.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib-base           3.2.2            py37h64f37c6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl                       2020.1                      216    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.3.0            py37hb782905_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.1.0            py37h45dec08_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.1.1            py37h47e9c7a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.19.0                   pypi_0    pypi
numpy-base                1.18.5           py37hc3f5095_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opencv                    3.4.2            py37h40b0b35_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openssl                   1.1.1g               he774522_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opt-einsum                3.2.1                    pypi_0    pypi
pandas                    1.0.5            py37h47e9c7a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pillow                    7.1.2            py37hcc1f983_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       20.1.1                   py37_1    defaults
protobuf                  3.12.2                   pypi_0    pypi
py-opencv                 3.4.2            py37hc319ecb_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyparsing                 2.4.7                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyqt                      5.9.2            py37h6538335_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python                    3.7.7                h81c818b_4    defaults
python-dateutil           2.8.1                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pytz                      2020.1                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
qt                        5.9.7            vc14h73c81de_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
requests                  2.24.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                47.3.1                   py37_0    defaults
sip                       4.19.8           py37h6538335_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.15.0                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.32.3               h2a8f88b_0    defaults
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow-gpu            2.2.0                    pypi_0    pypi
tensorflow-gpu-estimator  2.2.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               he774522_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tornado                   6.0.4            py37he774522_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
urllib3                   1.25.9                   pypi_0    pypi
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_3    defaults
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py37_0    defaults
wincertstore              0.2                      py37_0    defaults
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h62dcd97_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4    defaults
zstd                      1.4.4                ha9fde0e_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**问题**
在按照提示将权重文件放到相应文件夹后，设置好相关路径，我运行predict.py，输入图片路径
出现错误，一直traceback到tf_stack.extract_stack()，但未指出具体错误在哪里。
有人帮忙解答吗

具体运行结果如下：model_data/yolo4_weight.h5 model, anchors, and classes loaded.
Input image filename:people.jpg
2020-08-03 15:14:44.832473: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-08-03 15:14:46.176765: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
2020-08-03 15:14:46.399655: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-08-03 15:14:47.508150: W tensorflow/core/common_runtime/bfc_allocator.cc:311] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
2020-08-03 15:14:50.454673: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at conv_ops.cc:1110 : Not found: No algorithm worked!
2020-08-03 15:14:50.514161: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at conv_ops.cc:1110 : Not found: No algorithm worked!
2020-08-03 15:14:50.515266: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at conv_ops.cc:1110 : Not found: No algorithm worked!
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
	 [[{{node conv2d_93/Conv2D}}]]
	 [[boolean_mask_33/GatherV2/_3367]]
  (1) Not found: No algorithm worked!
	 [[{{node conv2d_93/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/studyfile/yolov4-tf2-master/predict.py", line 18, in <module>
    r_image = yolo.detect_image(image)
  File "D:\studyfile\yolov4-tf2-master\yolo.py", line 141, in detect_image
    K.learning_phase(): 0
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 958, in run
    run_metadata_ptr)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
	 [[node conv2d_93/Conv2D (defined at D:\studyfile\yolov4-tf2-master\nets\yolo4.py:86) ]]
	 [[boolean_mask_33/GatherV2/_3367]]
  (1) Not found: No algorithm worked!
	 [[node conv2d_93/Conv2D (defined at D:\studyfile\yolov4-tf2-master\nets\yolo4.py:86) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node conv2d_93/Conv2D:
 leaky_re_lu_20/LeakyRelu (defined at D:\studyfile\yolov4-tf2-master\utils\utils.py:15)

Input Source operations connected to node conv2d_93/Conv2D:
 leaky_re_lu_20/LeakyRelu (defined at D:\studyfile\yolov4-tf2-master\utils\utils.py:15)

Original stack trace for 'conv2d_93/Conv2D':
  File "D:/studyfile/yolov4-tf2-master/predict.py", line 8, in <module>
    yolo = YOLO()
  File "D:\studyfile\yolov4-tf2-master\yolo.py", line 50, in __init__
    self.generate()
  File "D:\studyfile\yolov4-tf2-master\yolo.py", line 85, in generate
    self.yolo_model = yolo_body(Input(shape=(None,None,3)), num_anchors//3, num_classes)
  File "D:\studyfile\yolov4-tf2-master\nets\yolo4.py", line 86, in yolo_body
    P3_output = DarknetConv2D(num_anchors * (num_classes + 5), (1, 1))(P3_output)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 207, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1106, in __call__
    return self.conv_op(inp, filter)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 638, in __call__
    return self.call(inp, filter)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 237, in __call__
    name=self.name)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2014, in conv2d
    name=name)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 969, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\framework\ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\framework\ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by 348872575** [comment]
> 我的环境：
> window10+pycharm
> conda 下的tensorflow-gpu2.2包含的库如下：
> Name Version Build Channel
> absl-py 0.9.0 pypi_0 pypi
> astunparse 1.6.3 pypi_0 pypi
> blas 1.0 mkl https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> ca-certificates 2020.6.24 0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> cachetools 4.1.1 pypi_0 pypi
> certifi 2020.6.20 py37_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> chardet 3.0.4 pypi_0 pypi
> cudatoolkit 10.1.243 h74a9793_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> cudnn 7.6.5 cuda10.1_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> cycler 0.10.0 py37_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> freetype 2.10.2 hd328e21_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> gast 0.3.3 pypi_0 pypi
> google-auth 1.18.0 pypi_0 pypi
> google-auth-oauthlib 0.4.1 pypi_0 pypi
> google-pasta 0.2.0 pypi_0 pypi
> grpcio 1.30.0 pypi_0 pypi
> h5py 2.10.0 pypi_0 pypi
> hdf5 1.8.20 hac2f561_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> icc_rt 2019.0.0 h0cc432a_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> icu 58.2 ha925a31_3 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> idna 2.10 pypi_0 pypi
> importlib-metadata 1.7.0 pypi_0 pypi
> intel-openmp 2020.1 216 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> joblib 0.16.0 pypi_0 pypi
> jpeg 9b hb83a4c4_2 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> keras-preprocessing 1.1.2 pypi_0 pypi
> kiwisolver 1.2.0 py37h74a9793_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> libopencv 3.4.2 h20b85fd_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> libpng 1.6.37 h2a8f88b_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> libtiff 4.1.0 h56a325e_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> lz4-c 1.9.2 h62dcd97_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> markdown 3.2.2 pypi_0 pypi
> matplotlib 3.2.2 0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> matplotlib-base 3.2.2 py37h64f37c6_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> mkl 2020.1 216 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> mkl-service 2.3.0 py37hb782905_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> mkl_fft 1.1.0 py37h45dec08_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> mkl_random 1.1.1 py37h47e9c7a_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> numpy 1.19.0 pypi_0 pypi
> numpy-base 1.18.5 py37hc3f5095_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> oauthlib 3.1.0 pypi_0 pypi
> olefile 0.46 py37_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> opencv 3.4.2 py37h40b0b35_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> openssl 1.1.1g he774522_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> opt-einsum 3.2.1 pypi_0 pypi
> pandas 1.0.5 py37h47e9c7a_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> pillow 7.1.2 py37hcc1f983_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> pip 20.1.1 py37_1 defaults
> protobuf 3.12.2 pypi_0 pypi
> py-opencv 3.4.2 py37hc319ecb_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> pyasn1 0.4.8 pypi_0 pypi
> pyasn1-modules 0.2.8 pypi_0 pypi
> pyparsing 2.4.7 py_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> pyqt 5.9.2 py37h6538335_2 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> python 3.7.7 h81c818b_4 defaults
> python-dateutil 2.8.1 py_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> pytz 2020.1 py_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> qt 5.9.7 vc14h73c81de_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> requests 2.24.0 pypi_0 pypi
> requests-oauthlib 1.3.0 pypi_0 pypi
> rsa 4.6 pypi_0 pypi
> scikit-learn 0.23.1 pypi_0 pypi
> scipy 1.4.1 pypi_0 pypi
> setuptools 47.3.1 py37_0 defaults
> sip 4.19.8 py37h6538335_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> six 1.15.0 py_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> sklearn 0.0 pypi_0 pypi
> sqlite 3.32.3 h2a8f88b_0 defaults
> tensorboard 2.2.2 pypi_0 pypi
> tensorboard-plugin-wit 1.7.0 pypi_0 pypi
> tensorflow-gpu 2.2.0 pypi_0 pypi
> tensorflow-gpu-estimator 2.2.0 pypi_0 pypi
> termcolor 1.1.0 pypi_0 pypi
> threadpoolctl 2.1.0 pypi_0 pypi
> tk 8.6.10 he774522_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> tornado 6.0.4 py37he774522_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> urllib3 1.25.9 pypi_0 pypi
> vc 14.1 h0510ff6_4 defaults
> vs2015_runtime 14.16.27012 hf0eaf9b_3 defaults
> werkzeug 1.0.1 pypi_0 pypi
> wheel 0.34.2 py37_0 defaults
> wincertstore 0.2 py37_0 defaults
> wrapt 1.12.1 pypi_0 pypi
> xz 5.2.5 h62dcd97_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> zipp 3.1.0 pypi_0 pypi
> zlib 1.2.11 h62dcd97_4 defaults
> zstd 1.4.4 ha9fde0e_3 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> 
> **问题**
> 在按照提示将权重文件放到相应文件夹后，设置好相关路径，我运行predict.py，输入图片路径
> 出现错误，一直traceback到tf_stack.extract_stack()，但未指出具体错误在哪里。
> 有人帮忙解答吗
> 
> 具体运行结果如下：model_data/yolo4_weight.h5 model, anchors, and classes loaded.
> Input image filename:people.jpg
> 2020-08-03 15:14:44.832473: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
> 2020-08-03 15:14:46.176765: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
> Relying on driver to perform ptx compilation.
> Modify $PATH to customize ptxas location.
> This message will be only logged once.
> 2020-08-03 15:14:46.399655: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
> 2020-08-03 15:14:47.508150: W tensorflow/core/common_runtime/bfc_allocator.cc:311] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
> 2020-08-03 15:14:50.454673: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at conv_ops.cc:1110 : Not found: No algorithm worked!
> 2020-08-03 15:14:50.514161: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at conv_ops.cc:1110 : Not found: No algorithm worked!
> 2020-08-03 15:14:50.515266: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at conv_ops.cc:1110 : Not found: No algorithm worked!
> Traceback (most recent call last):
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1365, in _do_call
> return fn(*args)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _run_fn
> target_list, run_metadata)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1443, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
> (0) Not found: No algorithm worked!
> [[{{node conv2d_93/Conv2D}}]]
> [[boolean_mask_33/GatherV2/_3367]]
> (1) Not found: No algorithm worked!
> [[{{node conv2d_93/Conv2D}}]]
> 0 successful operations.
> 0 derived errors ignored.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:/studyfile/yolov4-tf2-master/predict.py", line 18, in
> r_image = yolo.detect_image(image)
> File "D:\studyfile\yolov4-tf2-master\yolo.py", line 141, in detect_image
> K.learning_phase(): 0
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 958, in run
> run_metadata_ptr)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1181, in _run
> feed_dict_tensor, options, run_metadata)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _do_run
> run_metadata)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\client\session.py", line 1384, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
> (0) Not found: No algorithm worked!
> [[node conv2d_93/Conv2D (defined at D:\studyfile\yolov4-tf2-master\nets\yolo4.py:86) ]]
> [[boolean_mask_33/GatherV2/_3367]]
> (1) Not found: No algorithm worked!
> [[node conv2d_93/Conv2D (defined at D:\studyfile\yolov4-tf2-master\nets\yolo4.py:86) ]]
> 0 successful operations.
> 0 derived errors ignored.
> 
> Errors may have originated from an input operation.
> Input Source operations connected to node conv2d_93/Conv2D:
> leaky_re_lu_20/LeakyRelu (defined at D:\studyfile\yolov4-tf2-master\utils\utils.py:15)
> 
> Input Source operations connected to node conv2d_93/Conv2D:
> leaky_re_lu_20/LeakyRelu (defined at D:\studyfile\yolov4-tf2-master\utils\utils.py:15)
> 
> Original stack trace for 'conv2d_93/Conv2D':
> File "D:/studyfile/yolov4-tf2-master/predict.py", line 8, in
> yolo = YOLO()
> File "D:\studyfile\yolov4-tf2-master\yolo.py", line 50, in **init**
> self.generate()
> File "D:\studyfile\yolov4-tf2-master\yolo.py", line 85, in generate
> self.yolo_model = yolo_body(Input(shape=(None,None,3)), num_anchors//3, num_classes)
> File "D:\studyfile\yolov4-tf2-master\nets\yolo4.py", line 86, in yolo_body
> P3_output = DarknetConv2D(num_anchors * (num_classes + 5), (1, 1))(P3_output)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 778, in **call**
> outputs = call_fn(cast_inputs, *args, **kwargs)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 207, in call
> outputs = self._convolution_op(inputs, self.kernel)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1106, in **call**
> return self.conv_op(inp, filter)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 638, in **call**
> return self.call(inp, filter)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 237, in **call**
> name=self.name)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2014, in conv2d
> name=name)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 969, in conv2d
> data_format=data_format, dilations=dilations, name=name)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 744, in _apply_op_helper
> attrs=attr_protos, op_def=op_def)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\framework\ops.py", line 3327, in _create_op_internal
> op_def=op_def)
> File "C:\Users\Administrator.DESKTOP-5SSH0GF\anaconda3\envs\tensorflow2-2\lib\site-packages\tensorflow\python\framework\ops.py", line 1791, in **init**
> self._traceback = tf_stack.extract_stack()

**Comment by smallsun0801** [comment]
请问解决了吗

**Comment by yyyyam** [comment]
请问怎么解决的呢，我现在也是这个问题

**Comment by bubbliiiing** [comment]
一般是版本

**Comment by zdlovejy1314** [comment]
请问怎么解决呢

**Comment by bubbliiiing** [comment]
版本问题
