### ISSUE TITLE
在用yolo_voc_weights预训练权重之后再训练VOC数据集得到的权重文件训练效果mAP反而降低了好多是为什么呀？

### ISSUE THREAD

**Issue by guojialug** [bubbliiiing/yolov4-tf2#40]
![mAP2](https://user-images.githubusercontent.com/48385202/166853190-47de1bb4-6c3d-4d13-a6f0-28c7205d7f37.png)
上面是训练100个epoch得到的
![mAP1](https://user-images.githubusercontent.com/48385202/166853236-ec1d2c43-0e72-402b-8328-e3b1096c69a7.png)
这是yolo_voc_weights得到的

有什么解决方法吗？

**Comment by bubbliiiing** [comment]
你的mAP结果让我甚至不知道你的数据集怎么样的
具体训练策略我不知晓。

**Comment by guojialug** [comment]
我昨天仔细比较了一下，是我预训练权重文件的问题，我用的yolo_vco_weights的预训练权重去训练的VOC数据集，昨天改为yolo_weight后问题解决了，50epoch的map在86左右

**Comment by bubbliiiing** [comment]
也不应该啊…yolo_voc_weights也不应该变这么低

**Comment by bubbliiiing** [comment]
迷茫0

**Comment by guojialug** [comment]
但我确实训练之后是这样的，我也不太理解o(╥﹏╥)o

**Comment by bubbliiiing** [comment]
有可能是之前训练这个 voc的，我没加weight_decay，新代码加了之后，主要在训练weight_decay导致的问题，现在能用就行

**Comment by bubbliiiing** [comment]
之前没加导致各个权值都很大

**Comment by guojialug** [comment]
嗯嗯，谢谢大佬！
