### ISSUE TITLE
这个模型支持不载入预训练模型直接从0开始训练吗

### ISSUE THREAD

**Issue by 348872575** [bubbliiiing/yolov4-tf2#5]
这个模型支持不载入预训练模型直接从0开始训练吗？
如果可以能给出具体步骤吗

**Comment by bubbliiiing** [comment]
为什么不支持呢，只是你这样训练应该什么都检测不出来吧，你可以注释载入权重的部分吧，我

**Comment by 348872575** [comment]
> 为什么不支持呢，只是你这样训练应该什么都检测不出来吧，你可以注释载入权重的部分吧，我

谢谢回复。但是为什么从头开始训练会什么都检测不出来呢

**Comment by bubbliiiing** [comment]
迁移学习
