### ISSUE TITLE
請問電腦需求?

### ISSUE THREAD

**Issue by atisticbilly** [bubbliiiing/yolov4-tf2#7]
感謝作者提供資源,  
1.我嘗試執行image(416,416) batch_size=2, 發現會OOM,  後更改為(256,256) batch_size=1才可執行。
[作業系統 windows 10;  顯卡 RTX2060 內存6GB]
2.請問是在train.py中修改freeze_layer或是在哪裡設定，可以讀取更大的image_size?

如您能回覆, 非常謝謝~

**Comment by bubbliiiing** [comment]
1、解冻前爆显存？如果是的话这应该是tf2的小bug我觉得，冻结了反而需要更大的显存

**Comment by bubbliiiing** [comment]
2、那个你直接ctrl+F搜索freeze_layer即可

**Comment by atisticbilly** [comment]
謝謝您，我再試試看!
解凍數量調整後，可逐漸放大image size。
